AWSTemplateFormatVersion: '2010-09-09'
Description: Cloud9 environment for the ANZ Summit DevLabs.
Parameters:
  Cloud9EnvironmentName:
    Description: Chaos Engineering on ECS (Level 300)
    Type: String
    Default: Chaos-Engineering-on-ECS-Level300
  Cloud9InstanceType:
    Description: Cloud9 instance type
    Type: String
    Default: m5.large
  GitRepositoryURL:
    Description: The Git repository URL for the project we are cloning
    Type: String
    Default: https://github.com/aws-samples/aws-anz-devlabs-ecs-fis.git

Resources:
  Cloud9Instance:
    Description: "Cloud9 environment for the ANZ Summit DevLabs"
    Type: AWS::Cloud9::EnvironmentEC2
    Properties:
      Description: Run Chaos Engineering experiments on Amazon Elastic Container Service with AWS Fault Injection Simulator
      AutomaticStopTimeMinutes: 4320
      Name: 
        !Join [ "-", [ Ref: Cloud9EnvironmentName, Ref: AWS::StackName] ]
      InstanceType:
        Ref: Cloud9InstanceType
      Repositories:
        -
           PathComponent: /devlabs
           RepositoryUrl: !Ref GitRepositoryURL
      Tags: 
        - 
          Key: Environment
          Value: DevLabs

Outputs: 
  LabEnvironment:
    Description: Chaos Engineering on ECS (Level 300)
    Export:
      Name: 
        !Join [ "-", [ Ref: Cloud9EnvironmentName, Ref: AWS::StackName] ]
    Value:
      Fn::Join:
      - ''
      - - https://
        - Ref: AWS::Region
        - ".console.aws.amazon.com/cloud9/ide/"
        - Ref: Cloud9Instance
        - "?region="
        - Ref: AWS::Region